version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /src
    schedule:
      interval: daily

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: daily      
