version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/src" 
    schedule:
      interval: "weekly" 
      day: "monday"      
      time: "08:00"     
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels:
      - "dependencies"
    assignees:
      - "nataliagranato" 
